### ISSUE TITLE
Order by method

### ISSUE THREAD

**Issue by Yomguithereal** [shesek/cypher-query#2]
Hello @shesek. The order by method has to be called thusly for the time being (if I am not mistaking):

``` js
query['order by']('f.year');
```

This is not very elegant. Could we change that to:

``` js
query.orderBy('f.year');
```

I can do a PR for it if you want.

**Comment by shesek** [comment]
That's probably the least of the issues this library is facing (#1), but at least its an issue I can fix given my time constraints :) https://github.com/shesek/cypher-query/commit/3726a2957e44668794c6d058879201e5a205c9d5
